### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by GoodOldGamer** [Pelagicore/pelux-sde#17] opened 2018-06-21 09:05 UTC
I tried Head and 1.0 branch and it fails on my machine (Windows 10, Vagrant 2.1.1).

To reproduce:
`vagrant up`
on a new fresh install.

Result:
default: 2018-06-21 09:00:54 (6.80 MB/s) - ‘/tmp/qt-creator-installer-PcUa425k.run’ saved [125963924/125963924]
    default:
    default: QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
==> default: Running provisioner: shell...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 3: /opt/pelux_sdk/environment-setup*: No such file or directory
    default: /usr/bin/env:
    default: ‘python3\r’
    default: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I tried the Windows command shell and git bash with euqal results.

**Comment by GordanM** [comment] 2018-06-21 09:17
Hello @GoodOldGamer , thanks for reporting this issue! 

I believe back in the day we've seen this and the resolution was the following, I am copying the e-mail discussion between the members and the community. 

> 
> The error looks like it cannot run python as it adds the \r character sequence to the executable name. Not sure whether that's really the case or a printing error. I'm not at my pc, so I can't check that atm.
> 
> This was the problem. I'm running Windows and cloning the repository with Git Bash changed the line endings to Windows CRLF. I double-checked and this is the cause for the change.
> I used "Edit -> EOL Conversion -> Unix (LF)" in Notepad++ to convert the scripts back to Unix line endings and now I have the SDE up and running.

So the solution is to convert the script back to Unix line endings. 

Could you please try if this works for you?

**Comment by GoodOldGamer** [comment] 2018-06-21 10:47
Ok, line endings have been changed to Windows style. I changed the line endings of all shell scripts to Unix style. The installation still fails but with a slightly different message:

efault: QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
==> default: Running provisioner: shell...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 3: /opt/pelux_sdk/environment-setup*: No such file or directory
    default: Traceback (most recent call last):
    default:   File "/vagrant/sde-cookbook/qtcreator/configure-qtcreator.py", line 147, in <module>
    default:     bootstrapper = QtCreatorBootstrapper(sys.argv[1])
    default:   File "/vagrant/sde-cookbook/qtcreator/configure-qtcreator.py", line 44, in __init__
    default:     arch_env_var = os.environ["ARCH"]
    default:   File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    default:     raise KeyError(key) from None
    default: KeyError: 'ARCH'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by GordanM** [comment] 2018-06-24 14:09
@GoodOldGamer thanks, at least that's an improvement. @AshleyNair could you put this issue in the team backlog? I guess the majority of the work here is to follow up and see what could've gone wrong. Maybe @Gagi2k has some quick hints?

**Comment by sashko** [comment] 2018-06-24 20:40
@GoodOldGamer is it possible that you've run the installation as a root first and then tried to continue as a non-root?

> default: /tmp/vagrant-shell: line 3: /opt/pelux_sdk/environment-setup*: No such file or directory

I would need to take a look into SDK installation, but it seems like it was not complete. Could you delete all the artifacts and restart it as a non-root user, please? Thanks.

**Comment by GoodOldGamer** [comment] 2018-06-25 07:46
I'm pretty sure I used all the time the Windows command line / Git shell without administrator privileges.

I did as you said:
- vagrant destroy & deleted the whole .vagrant folder
- started a normal Windows command line without administrator privileges
- vagrant up
-> same error

What do you need?

Edit:
Attached installation log
[vagrant_install.log](https://github.com/Pelagicore/pelux-sde/files/2132180/vagrant_install.log)

**Comment by TSAnsari** [comment] 2018-06-26 10:21
@GoodOldGamer You need to build the sdk installer first. See 
http://pelux.io/software-factory/master/swf-blueprint/docs/articles/baseplatform/creating-sdk.html#building-the-sdk

Then copy the generated file in tmp/deploy/sdk to the location where you are running the vagrant. Or alternatively run,

SDK_FILE_NAME="<sdk_installer_filepath>" vagrant up

**Comment by GoodOldGamer** [comment] 2018-06-26 10:39
@TSAnsari 
Are you sure? There's nothing mentioned in the readme.md from building the sdk installer first.

So I need a Linux VM first to bitbake the installer... Or is there a way to do so in Windows? :/

**Comment by TSAnsari** [comment] 2018-06-26 11:24
@GoodOldGamer I am afraid you have to bitbake the installer on a linux machine/VM first. The sdk is not bundled with the sde. You can read about it here http://pelux.io/software-factory/master/chapters/sde/index.html

Alternatively, if you can get access to a linux machine/VM set up, then you can bitbake and install SDK directly on to it as described here http://pelux.io/software-factory/master/swf-blueprint/docs/articles/sdk/installing-the-sdk.html. In this case you also have to install the QtCreator and DLT Viewer manually, as they are installed additionally when installing using sde installation process.

**Comment by GordanM** [comment] 2018-06-26 16:06
Afaik, there is a mock SDK provided with the SDE that proves its sanity and as such there is no need to build the full SDK to provide the support for this issue. Could you please verify this with Viktor, Tariq? Furthermore, if you would like to build a SDE environment with a functioning cross-compiler, you would need to build the image and yocto sdk for it.

**Comment by GoodOldGamer** [comment] 2018-06-27 07:56
Ok. I'd like to build a full SDK following the description on
[Building PELUX sources](http://pelux.io/software-factory/master/chapters/baseplatform/building-PELUX-sources.html). But even this fails ...

Machine is a VM with Ubuntu 14.04.5 LTS with repo version v1.12.37:

:~$ repo init -u https://github.com/Pelagicore/pelux-manifests -b pyro

Result:
  cp /home/vagrant/pelux/.repo/repo/repo /usr/bin/repo
  repo has been initialized in /home/vagrant/pelux

:~$ repo sync

Result:
   cp /home/vagrant/pelux/.repo/repo/repo /usr/bin/repo

  Fetching project GENIVI/meta-ivi
  Fetching project yocto/meta-boot2qt
  Fetching project poky
  Fetching project Pelagicore/meta-template

  fatal: unable to connect to code.qt.io:
  code.qt.io[0: 52.212.35.92]: errno=Connection timed out

  fatal: unable to connect to github.com:
  github.com[0: 192.30.253.112]: errno=Connection timed out
  github.com[1: 192.30.253.113]: errno=Connection timed out

  fatal: unable to connect to git.yoctoproject.org:
  git.yoctoproject.org[0: 140.211.169.56]: errno=Connection timed out

  error: Cannot fetch yocto/meta-boot2qt
  error: Cannot fetch poky
  error: Cannot fetch GENIVI/meta-ivi
  error: Cannot fetch Pelagicore/meta-template
  error: Cannot fetch meta-virtualization

But a ping to all of these IPs works. Frustrating.
I know that this issue doesn't belong in this ticket. Where can I get help?

**Comment by sashko** [comment] 2018-06-27 11:57
@GoodOldGamer the manifest file points into the right address and `code.qt.io` as well as the other sites are up and running, therefore the issue is on your side: most likely ssh port is blocked by your firewall. Try to use https instead by applying the following patch:

```
diff --git a/pelux.xml b/pelux.xml
index 1b15af0..dc19bab 100644
--- a/pelux.xml
+++ b/pelux.xml
@@ -6,14 +6,14 @@
 
   <!-- Remotes -->
   <remote fetch="git://git.openembedded.org"    name="oe"/>
-  <remote fetch="git://git.yoctoproject.org"    name="yocto"/>
-  <remote fetch="git://github.com/"             name="github"/>
-  <remote fetch="git://code.qt.io/"             name="code.qt"/>
+  <remote fetch="https://git.yoctoproject.org"    name="yocto"/>
+  <remote fetch="https://github.com/"             name="github"/>
+  <remote fetch="https://code.qt.io/"           name="code.qt"/>
 
   <!-- Base stuff -->
-  <project remote="oe"
+  <project remote="github"
            revision="5e82995148a2844c6f483ae5ddd1438d87ea9fb7"
-           name="meta-openembedded"
+           name="openembedded/meta-openembedded"
            path="sources/meta-openembedded"/>
 
   <project remote="yocto"
```

**Comment by GoodOldGamer** [comment] 2018-06-27 13:01
@sashko 
Thanks, this was the solution to this problem. Damn company network ...

**Comment by Mibez** [comment] 2018-08-21 11:38
I had the same initial problem with the installation, the script seemed to be unable to find the sdk even though I ran the `SDK_FILE_NAME=<sdk_installer_filepath>` before  `vagrant up`.

For me the issue was fixed by hardcoding the sdk file path to the vagrantfile (around line 21):

`def install_sdk(config)`
     `sdk_file_name = "<my sdk filename " `

**Comment by sashko** [comment] 2018-08-21 12:28
@mibez could you please clarify which version you have used?

**Comment by Mibez** [comment] 2018-08-21 12:43
Pelux v2.0, on Windows 10 with Vagrant v2.0.4

**Comment by sashko** [comment] 2018-08-21 12:51
Thanks, we'll take a look into it. Just need to find a Windows machine 🤔

**Comment by sashko** [comment] 2018-09-23 17:01
@Mibez one has to put SDK installer into the same folder, and specify its not, not a path. It is now clearly stated in the documentation:

> To start the SDE VM, check out the repository, put the SDK into its root directory and from that directory (the same directory as the Vagrantfile is located in) run:
> 
> SDK_FILE_NAME=\<SDK installer\> vagrant up

Thank you for the report!

**Closed as completed by sashko** 2018-09-23 17:01 UTC
